In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['train.csv', 'sample_submission.csv', 'test.csv']


In [2]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.preprocessing import StandardScaler

In [3]:
# Read traning dataset
train = pd.read_csv("../input/train.csv")
train.head()

ID_code  target    var_0   var_1   ...     var_196  var_197  var_198  var_199
0  train_0       0   8.9255 -6.7863   ...      7.8784   8.5635  12.7803  -1.0914
1  train_1       0  11.5006 -4.1473   ...      8.1267   8.7889  18.3560   1.9518
2  train_2       0   8.6093 -2.7457   ...     -6.5213   8.2675  14.7222   0.3965
3  train_3       0  11.0604 -2.1518   ...     -2.9275  10.2922  17.9697  -8.9996
4  train_4       0   9.8369 -1.4834   ...      3.9267   9.5031  17.9974  -8.8104

[5 rows x 202 columns]

In [4]:
X_train = train.iloc[:,2:].values
y_train = train.iloc[:,1].values
scaler = StandardScaler()
x_train = scaler.fit_transform(X_train)

print("x_train shape:", x_train.shape, "y_train:", y_train.shape)
x_train[:3]

x_train shape: (200000, 200) y_train: (200000,)


array([[-5.77101737e-01, -1.27373702e+00,  4.51707280e-01,
        -8.33708981e-01,  2.35571466e-01, -5.36430115e-01,
        -3.34926118e-01,  6.08750528e-01, -1.56158029e+00,
        -1.47379584e+00,  4.60091096e-01,  1.07662306e+00,
        -5.40769529e-02, -1.71477344e+00,  5.61098098e-01,
        -9.77837595e-03, -1.40163593e+00, -2.29802163e-01,
        -1.39593983e+00,  2.28529175e+00, -4.68989437e-01,
        -1.26734255e-01, -6.06165829e-01, -1.03994676e+00,
         1.00568250e+00, -8.23003171e-01, -1.84672529e-01,
         4.79492372e-01, -7.68963809e-01,  3.60340166e-01,
         9.26437464e-01,  1.16258685e+00, -1.29982397e+00,
         4.89773138e-01, -4.47274675e-01,  1.30050023e+00,
        -4.84244898e-01,  8.97088021e-01, -1.39649018e+00,
         7.89253926e-01,  1.79582362e-01, -3.24222704e-01,
         5.09122596e-01,  1.53310132e+00,  4.56290809e-01,
         2.65484911e-01, -1.88913873e+00, -1.64639886e-01,
         1.16264232e-01, -1.44571926e+00,  2.57932906e-0

In [5]:
xTrain, xTest, yTrain, yTest = train_test_split(x_train, y_train, test_size = 0.10, random_state = 2019)
print("xTrain shape:", xTrain.shape, "yTrain:", yTrain.shape, "xTest shape:", xTest.shape, "yTest shape: ", yTest.shape)

xTrain shape: (180000, 200) yTrain: (180000,) xTest shape: (20000, 200) yTest shape:  (20000,)


In [6]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(xTrain, yTrain)

In [7]:
#Predict the response for test dataset
y_pred = clf.predict(xTest)

In [12]:
y_pred[:3]

array([0, 0, 0])

In [8]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(yTest, y_pred))

Accuracy: 0.83595


In [9]:
# Read test dataset
test = pd.read_csv('../input/test.csv')

In [13]:
X_test = test.iloc[:,1:].values
x_test = scaler.fit_transform(X_test)
print(x_test.shape)
x_test[:3]

(200000, 200)


array([[ 1.33981567e-01,  2.32744611e+00,  8.52789962e-01,
         1.28657975e+00,  2.20421535e-01,  3.39301688e-01,
         5.02074634e-01,  5.07627636e-01,  5.56963994e-01,
         1.00708695e+00, -4.34977006e-01, -1.82313471e-01,
        -2.79168189e-01, -1.77049090e+00,  3.59043698e-03,
        -1.78827864e-01, -6.36134285e-01, -1.98437161e+00,
         4.01204313e-02,  4.65547179e-01, -1.62971673e+00,
         1.92174361e-01, -9.52565286e-01,  8.65483842e-02,
        -1.09163043e+00,  1.58425222e+00, -9.26106297e-01,
        -6.96609812e-01,  2.29175276e-01, -4.83069972e-01,
         7.38825824e-01, -5.28873550e-01,  1.00070927e+00,
        -4.59434980e-01, -1.87529421e-01,  8.26996722e-01,
        -7.28780314e-01, -1.03753218e+00, -2.03577817e-01,
         1.98349166e+00, -1.07177417e+00,  1.61598878e+00,
         9.30696431e-02,  8.62228506e-01,  7.46962373e-01,
        -9.02832183e-01,  3.06846575e-01,  2.01490492e+00,
         2.20997505e-01,  2.07589466e-02,  4.45738757e-0

In [14]:
predictions = clf.predict(x_test)

In [18]:
ans = pd.DataFrame(predictions)
ans = ans[0]
test_id = test["ID_code"]
sub = pd.DataFrame()
sub['ID_code'] = test_id
sub['target'] = ans

In [ ]:
sub.to_csv('submission_dt1.csv', index=False)