##Importing data

In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler , RobustScaler

from sklearn.model_selection import GridSearchCV , train_test_split , cross_val_score

from sklearn.linear_model import LogisticRegression
import os
import warnings
warnings.filterwarnings('ignore')
train = pd.read_csv('../input/train.csv' , index_col = 'id')
test = pd.read_csv('../input/test.csv'  , index_col = 'id')

print(os.listdir("../input/"))


['sample_submission.csv', 'test.csv', 'train.csv']


In [2]:
y = train['target']
train = train.drop(['target'] , axis = 1)
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 250 entries, 0 to 249
Columns: 300 entries, 0 to 299
dtypes: float64(300)
memory usage: 587.9 KB


In [3]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19750 entries, 250 to 19999
Columns: 300 entries, 0 to 299
dtypes: float64(300)
memory usage: 45.4 MB


In [4]:
train.head()

0      1      2      3      4  ...      295    296    297    298    299
id                                     ...                                     
0  -0.098  2.165  0.681 -0.614  1.309  ...   -2.097  1.051 -0.414  1.038 -1.065
1   1.081 -0.973 -0.383  0.326 -0.428  ...   -1.624 -0.458 -1.099 -0.936  0.973
2  -0.523 -0.089 -0.348  0.148 -0.022  ...   -1.165 -1.544  0.004  0.800 -1.211
3   0.067 -0.021  0.392 -1.637 -0.446  ...    0.467 -0.562 -0.254 -0.533  0.238
4   2.347 -0.831  0.511 -0.021  1.225  ...    1.378  1.246  1.478  0.428  0.253

[5 rows x 300 columns]

In [5]:
scaler = StandardScaler()
train = scaler.fit_transform(train)
test = scaler.fit_transform(test)


In [6]:
clf = LogisticRegression(class_weight='balanced', solver='liblinear', penalty ='l1', C= 0.1, max_iter=10000)
clf.fit(train, y)
scores = cross_val_score(clf, train, y, cv=5)
scores

array([0.7 , 0.7 , 0.68, 0.68, 0.74])

In [7]:
clf.fit(train, y)
ans = clf.predict_proba(test)
ans

array([[0.33307651, 0.66692349],
       [0.53016248, 0.46983752],
       [0.48450817, 0.51549183],
       ...,
       [0.71699864, 0.28300136],
       [0.22331564, 0.77668436],
       [0.77002717, 0.22997283]])

In [8]:
submit = pd.read_csv('../input/sample_submission.csv')
submit.head()

id  target
0  250       0
1  251       0
2  252       0
3  253       0
4  254       0

In [9]:
ans

array([[0.33307651, 0.66692349],
       [0.53016248, 0.46983752],
       [0.48450817, 0.51549183],
       ...,
       [0.71699864, 0.28300136],
       [0.22331564, 0.77668436],
       [0.77002717, 0.22997283]])

Required result is stored in second column so, let's extract it .

In [10]:
submit['target'] = ans[:,1]

Create submition file

In [11]:
submit.to_csv('submit.csv', index = False)