In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['test.csv', 'sampleSubmission.csv', 'train.csv']


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
train = pd.read_csv('../input/train.csv')
test = pd.read_csv('../input/test.csv')

In [4]:
train = train.drop(['Soil_Type7', 'Soil_Type15'], axis=1)
test = test.drop(['Soil_Type7', 'Soil_Type15'], axis=1)

In [6]:
test.describe()

Id      Elevation      ...          Soil_Type39    Soil_Type40
count  565892.000000  565892.000000      ...        565892.000000  565892.000000
mean   298066.500000    2964.977407      ...             0.023236       0.014651
std    163359.093603     273.157030      ...             0.150652       0.120152
min     15121.000000    1859.000000      ...             0.000000       0.000000
25%    156593.750000    2818.000000      ...             0.000000       0.000000
50%    298066.500000    2999.000000      ...             0.000000       0.000000
75%    439539.250000    3164.000000      ...             0.000000       0.000000
max    581012.000000    3858.000000      ...             1.000000       1.000000

[8 rows x 53 columns]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train.drop('Cover_Type',axis=1), 
                                                    train['Cover_Type'], test_size=0.30, 
                                                    random_state=101)

In [9]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=50)
rfc.fit(X_train,y_train)
pred_rfc = rfc.predict(X_test)

In [10]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,pred_rfc))
print(confusion_matrix(y_test,pred_rfc))

              precision    recall  f1-score   support

           1       0.79      0.77      0.78       668
           2       0.78      0.68      0.73       656
           3       0.83      0.79      0.81       647
           4       0.93      0.97      0.95       642
           5       0.88      0.94      0.91       634
           6       0.82      0.86      0.84       620
           7       0.94      0.97      0.96       669

   micro avg       0.86      0.86      0.86      4536
   macro avg       0.85      0.86      0.85      4536
weighted avg       0.85      0.86      0.85      4536

[[517  93   2   0  14   3  39]
 [123 449  21   0  43  17   3]
 [  0   4 514  32  16  81   0]
 [  0   0  10 622   0  10   0]
 [  0  22   9   0 595   8   0]
 [  0   1  63  18   5 533   0]
 [ 14   3   0   0   0   0 652]]


In [11]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=50)
rfc.fit(train.drop('Cover_Type',axis=1),train['Cover_Type'])
pred_rfc = rfc.predict(test)

In [12]:
submission= pd.DataFrame({
    "Id" : test["Id"],
    'Cover_Type' : pred_rfc
})

submission.to_csv('submission.csv',index=False)